using Cirrious.MvvmCross.Plugins.Sqlite;
using System.Collections.Generic;

namespace InfiMobile.Core.Models
{
    public class Country : Model
    {
        [Indexed(Name = "country_idx_1", Unique = true)]
        public int ID { get; set; }

        [MaxLength(50)]
        public string Land { get; set; }

        [MaxLength(3)]
        public string Code3 { get; set; }

        [MaxLength(2)]
        public string Code2 { get; set; }

        public override string ToString()
        {
            return string.Format("{0} - {1}", Code2, Land);
        }

        public Country()
            : base()
        {
        }

        public Country(int id, string land, string code3, string code2)
        {
            ID = id;
            Land = land;
            Code3 = code3;
            Code2 = code2;
        }

        public static List<Country> List()
        {
            return new List<Country> 
            {
                new Country(1, "Afghanistan", "AFG", "AF"),
                new Country(2, "Albania", "ALB", "AL"),
                new Country(3, "Algeria", "DZA", "DZ"),
                new Country(4, "American Samoa", "ASM", "AS"),
                new Country(5, "Andorra", "AND", "AD"),
                new Country(6, "Angola", "AGO", "AO"),
                new Country(7, "Anguilla", "AIA", "AI"),
                new Country(8, "Antarctica", "ATA", "AQ"),
                new Country(9, "Antigua and Barbuda", "ATG", "AG"),
                new Country(10, "Argentina", "ARG", "AR"),
                new Country(11, "Armenia", "ARM", "AM"),
                new Country(12, "Aruba", "ABW", "AW"),
                new Country(13, "Australia", "AUS", "AU"),
                new Country(14, "Austria", "AUT", "AT"),
                new Country(15, "Azerbaijan", "AZE", "AZ"),
                new Country(16, "Bahamas", "BHS", "BS"),
                new Country(17, "Bahrain", "BHR", "BH"),
                new Country(18, "Bangladesh", "BGD", "BD"),
                new Country(19, "Barbados", "BRB", "BB"),
                new Country(20, "Belarus", "BLR", "BY"),
                new Country(21, "Belgium", "BEL", "BE"),
                new Country(22, "Belize", "BLZ", "BZ"),
                new Country(23, "Benin", "BEN", "BJ"),
                new Country(24, "Bermuda", "BMU", "BM"),
                new Country(25, "Bhutan", "BTN", "BT"),
                new Country(26, "Bolivia", "BOL", "BO"),
                new Country(27, "Bosnia and Herzegowina", "BIH", "BA"),
                new Country(28, "Botswana", "BWA", "BW"),
                new Country(29, "Bouvet Island", "BVT", "BV"),
                new Country(30, "Brazil", "BRA", "BR"),
                new Country(31, "British Indian Ocean Territory", "IOT", "IO"),
                new Country(32, "Brunei Darussalam", "BRN", "BN"),
                new Country(33, "Bulgaria", "BGR", "BG"),
                new Country(34, "Burkina Faso", "BFA", "BF"),
                new Country(35, "Burundi", "BDI", "BI"),
                new Country(36, "Cambodia", "KHM", "KH"),
                new Country(37, "Cameroon", "CMR", "CM"),
                new Country(38, "Canada", "CAN", "CA"),
                new Country(39, "Cape Verde", "CPV", "CV"),
                new Country(40, "Cayman Islands", "CYM", "KY"),
                new Country(41, "Central African Republic", "CAF", "CF"),
                new Country(42, "Chad", "TCD", "TD"),
                new Country(43, "Chile", "CHL", "CL"),
                new Country(44, "China", "CHN", "CN"),
                new Country(45, "Christmas Island", "CXR", "CX"),
                new Country(46, "Cocos (Keeling) Islands", "CCK", "CC"),
                new Country(47, "Colombia", "COL", "CO"),
                new Country(48, "Comoros", "COM", "KM"),
                new Country(49, "Congo", "COG", "CG"),
                new Country(50, "Cook Islands", "COK", "CK"),
                new Country(51, "Costa Rica", "CRI", "CR"),
                new Country(52, "Cote D''Ivoire", "CIV", "CI"),
                new Country(53, "Croatia", "HRV", "HR"),
                new Country(54, "Cuba", "CUB", "CU"),
                new Country(55, "Cyprus", "CYP", "CY"),
                new Country(56, "Czech Republic", "CZE", "CZ"),
                new Country(57, "Denmark", "DNK", "DK"),
                new Country(58, "Djibouti", "DJI", "DJ"),
                new Country(59, "Dominica", "DMA", "DM"),
                new Country(60, "Dominican Republic", "DOM", "DO"),
                new Country(61, "East Timor", "TMP", "TP"),
                new Country(62, "Ecuador", "ECU", "EC"),
                new Country(63, "Egypt", "EGY", "EG"),
                new Country(64, "El Salvador", "SLV", "SV"),
                new Country(65, "Equatorial Guinea", "GNQ", "GQ"),
                new Country(66, "Eritrea", "ERI", "ER"),
                new Country(67, "Estonia", "EST", "EE"),
                new Country(68, "Ethiopia", "ETH", "ET"),
                new Country(69, "Falkland Islands (Malvinas)", "FLK", "FK"),
                new Country(70, "Faroe Islands", "FRO", "FO"),
                new Country(71, "Fiji", "FJI", "FJ"),
                new Country(72, "Finland", "FIN", "FI"),
                new Country(73, "France", "FRA", "FR"),
                new Country(74, "France, Metropolitan", "FXX", "FX"),
                new Country(75, "French Guiana", "GUF", "GF"),
                new Country(76, "French Polynesia", "PYF", "PF"),
                new Country(77, "French Southern Territories", "ATF", "TF"),
                new Country(78, "Gabon", "GAB", "GA"),
                new Country(79, "Gambia", "GMB", "GM"),
                new Country(80, "Georgia", "GEO", "GE"),
                new Country(81, "Germany", "DEU", "DE"),
                new Country(82, "Ghana", "GHA", "GH"),
                new Country(83, "Gibraltar", "GIB", "GI"),
                new Country(84, "Greece", "GRC", "GR"),
                new Country(85, "Greenland", "GRL", "GL"),
                new Country(86, "Grenada", "GRD", "GD"),
                new Country(87, "Guadeloupe", "GLP", "GP"),
                new Country(88, "Guam", "GUM", "GU"),
                new Country(89, "Guatemala", "GTM", "GT"),
                new Country(90, "Guinea", "GIN", "GN"),
                new Country(91, "Guinea-bissau", "GNB", "GW"),
                new Country(92, "Guyana", "GUY", "GY"),
                new Country(93, "Haiti", "HTI", "HT"),
                new Country(94, "Heard and Mc Donald Islands", "HMD", "HM"),
                new Country(95, "Honduras", "HND", "HN"),
                new Country(96, "Hong Kong", "HKG", "HK"),
                new Country(97, "Hungary", "HUN", "HU"),
                new Country(98, "Iceland", "ISL", "IS"),
                new Country(99, "India", "IND", "IN"),
                new Country(100, "Indonesia", "IDN", "ID"),
                new Country(101, "Iran (Islamic Republic of)", "IRN", "IR"),
                new Country(102, "Iraq", "IRQ", "IQ"),
                new Country(103, "Ireland", "IRL", "IE"),
                new Country(104, "Israel", "ISR", "IL"),
                new Country(105, "Italy", "ITA", "IT"),
                new Country(106, "Jamaica", "JAM", "JM"),
                new Country(107, "Japan", "JPN", "JP"),
                new Country(108, "Jordan", "JOR", "JO"),
                new Country(109, "Kazakhstan", "KAZ", "KZ"),
                new Country(110, "Kenya", "KEN", "KE"),
                new Country(111, "Kiribati", "KIR", "KI"),
                new Country(112, "Korea, Democratic People''s Republic of", "PRK", "KP"),
                new Country(113, "Korea, Republic of", "KOR", "KR"),
                new Country(114, "Kuwait", "KWT", "KW"),
                new Country(115, "Kyrgyzstan", "KGZ", "KG"),
                new Country(116, "Lao People''s Democratic Republic", "LAO", "LA"),
                new Country(117, "Latvia", "LVA", "LV"),
                new Country(118, "Lebanon", "LBN", "LB"),
                new Country(119, "Lesotho", "LSO", "LS"),
                new Country(120, "Liberia", "LBR", "LR"),
                new Country(121, "Libyan Arab Jamahiriya", "LBY", "LY"),
                new Country(122, "Liechtenstein", "LIE", "LI"),
                new Country(123, "Lithuania", "LTU", "LT"),
                new Country(124, "Luxembourg", "LUX", "LU"),
                new Country(125, "Macau", "MAC", "MO"),
                new Country(126, "Macedonia, The Former Yugoslav Republic of", "MKD", "MK"),
                new Country(127, "Madagascar", "MDG", "MG"),
                new Country(128, "Malawi", "MWI", "MW"),
                new Country(129, "Malaysia", "MYS", "MY"),
                new Country(130, "Maldives", "MDV", "MV"),
                new Country(131, "Mali", "MLI", "ML"),
                new Country(132, "Malta", "MLT", "MT"),
                new Country(133, "Marshall Islands", "MHL", "MH"),
                new Country(134, "Martinique", "MTQ", "MQ"),
                new Country(135, "Mauritania", "MRT", "MR"),
                new Country(136, "Mauritius", "MUS", "MU"),
                new Country(137, "Mayotte", "MYT", "YT"),
                new Country(138, "Mexico", "MEX", "MX"),
                new Country(139, "Micronesia, Federated States of", "FSM", "FM"),
                new Country(140, "Moldova, Republic of", "MDA", "MD"),
                new Country(141, "Monaco", "MCO", "MC"),
                new Country(142, "Mongolia", "MNG", "MN"),
                new Country(143, "Montserrat", "MSR", "MS"),
                new Country(144, "Morocco", "MAR", "MA"),
                new Country(145, "Mozambique", "MOZ", "MZ"),
                new Country(146, "Myanmar", "MMR", "MM"),
                new Country(147, "Namibia", "NAM", "NA"),
                new Country(148, "Nauru", "NRU", "NR"),
                new Country(149, "Nepal", "NPL", "NP"),
                new Country(150, "Netherlands", "NLD", "NL"),
                new Country(151, "Netherlands Antilles", "ANT", "AN"),
                new Country(152, "New Caledonia", "NCL", "NC"),
                new Country(153, "New Zealand", "NZL", "NZ"),
                new Country(154, "Nicaragua", "NIC", "NI"),
                new Country(155, "Niger", "NER", "NE"),
                new Country(156, "Nigeria", "NGA", "NG"),
                new Country(157, "Niue", "NIU", "NU"),
                new Country(158, "Norfolk Island", "NFK", "NF"),
                new Country(159, "Northern Mariana Islands", "MNP", "MP"),
                new Country(160, "Norway", "NOR", "NO"),
                new Country(161, "Oman", "OMN", "OM"),
                new Country(162, "Pakistan", "PAK", "PK"),
                new Country(163, "Palau", "PLW", "PW"),
                new Country(164, "Panama", "PAN", "PA"),
                new Country(165, "Papua New Guinea", "PNG", "PG"),
                new Country(166, "Paraguay", "PRY", "PY"),
                new Country(167, "Peru", "PER", "PE"),
                new Country(168, "Philippines", "PHL", "PH"),
                new Country(169, "Pitcairn", "PCN", "PN"),
                new Country(170, "Poland", "POL", "PL"),
                new Country(171, "Portugal", "PRT", "PT"),
                new Country(172, "Puerto Rico", "PRI", "PR"),
                new Country(173, "Qatar", "QAT", "QA"),
                new Country(174, "Reunion", "REU", "RE"),
                new Country(175, "Romania", "ROM", "RO"),
                new Country(176, "Russian Federation", "RUS", "RU"),
                new Country(177, "Rwanda", "RWA", "RW"),
                new Country(178, "Saint Kitts and Nevis", "KNA", "KN"),
                new Country(179, "Saint Lucia", "LCA", "LC"),
                new Country(180, "Saint Vincent and the Grenadines", "VCT", "VC"),
                new Country(181, "Samoa", "WSM", "WS"),
                new Country(182, "San Marino", "SMR", "SM"),
                new Country(183, "Sao Tome and Principe", "STP", "ST"),
                new Country(184, "Saudi Arabia", "SAU", "SA"),
                new Country(185, "Senegal", "SEN", "SN"),
                new Country(186, "Seychelles", "SYC", "SC"),
                new Country(187, "Sierra Leone", "SLE", "SL"),
                new Country(188, "Singapore", "SGP", "SG"),
                new Country(189, "Slovakia (Slovak Republic)", "SVK", "SK"),
                new Country(190, "Slovenia", "SVN", "SI"),
                new Country(191, "Solomon Islands", "SLB", "SB"),
                new Country(192, "Somalia", "SOM", "SO"),
                new Country(193, "South Africa", "ZAF", "ZA"),
                new Country(194, "South Georgia and the South Sandwich Islands", "SGS", "GS"),
                new Country(195, "Spain", "ESP", "ES"),
                new Country(196, "Sri Lanka", "LKA", "LK"),
                new Country(197, "St. Helena", "SHN", "SH"),
                new Country(198, "St. Pierre and Miquelon", "SPM", "PM"),
                new Country(199, "Sudan", "SDN", "SD"),
                new Country(200, "Suriname", "SUR", "SR"),
                new Country(201, "Svalbard and Jan Mayen Islands", "SJM", "SJ"),
                new Country(202, "Swaziland", "SWZ", "SZ"),
                new Country(203, "Sweden", "SWE", "SE"),
                new Country(204, "Switzerland", "CHE", "CH"),
                new Country(205, "Syrian Arab Republic", "SYR", "SY"),
                new Country(206, "Taiwan", "TWN", "TW"),
                new Country(207, "Tajikistan", "TJK", "TJ"),
                new Country(208, "Tanzania, United Republic of", "TZA", "TZ"),
                new Country(209, "Thailand", "THA", "TH"),
                new Country(210, "Togo", "TGO", "TG"),
                new Country(211, "Tokelau", "TKL", "TK"),
                new Country(212, "Tonga", "TON", "TO"),
                new Country(213, "Trinidad and Tobago", "TTO", "TT"),
                new Country(214, "Tunisia", "TUN", "TN"),
                new Country(215, "Turkey", "TUR", "TR"),
                new Country(216, "Turkmenistan", "TKM", "TM"),
                new Country(217, "Turks and Caicos Islands", "TCA", "TC"),
                new Country(218, "Tuvalu", "TUV", "TV"),
                new Country(219, "Uganda", "UGA", "UG"),
                new Country(220, "Ukraine", "UKR", "UA"),
                new Country(221, "United Arab Emirates", "ARE", "AE"),
                new Country(222, "United Kingdom", "GBR", "GB"),
                new Country(223, "United States", "USA", "US"),
                new Country(224, "United States Minor Outlying Islands", "UMI", "UM"),
                new Country(225, "Uruguay", "URY", "UY"),
                new Country(226, "Uzbekistan", "UZB", "UZ"),
                new Country(227, "Vanuatu", "VUT", "VU"),
                new Country(228, "Vatican City State (Holy See)", "VAT", "VA"),
                new Country(229, "Venezuela", "VEN", "VE"),
                new Country(230, "Viet Nam", "VNM", "VN"),
                new Country(231, "Virgin Islands (British)", "VGB", "VG"),
                new Country(232, "Virgin Islands (U.S.)", "VIR", "VI"),
                new Country(233, "Wallis and Futuna Islands", "WLF", "WF"),
                new Country(234, "Western Sahara", "ESH", "EH"),
                new Country(235, "Yemen", "YEM", "YE"),
                new Country(236, "Yugoslavia", "YUG", "YU"),
                new Country(237, "The Democratic Republic of Congo", "DRC", "DC"),
                new Country(238, "Zambia", "ZMB", "ZM"),
                new Country(239, "Zimbabwe", "ZWE", "ZW"),
                new Country(240, "East Timor", "XET", "XE"),
                new Country(241, "Jersey", "XJE", "XJ"),
                new Country(242, "St. Barthelemy", "XSB", "XB"),
                new Country(243, "St. Eustatius", "XSE", "XU"),
                new Country(244, "Canary Islands", "XCA", "XC")
            };
        }
    }
}
