#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("InfiMobile.Droid.Resource", IsApplication=true)]

namespace InfiMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxDropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int MvxItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MvxSource = 2130771972;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditPatient = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int spinner_genderitem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int spinner_genders = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int cancel = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int care = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int dateofbirth = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int firstname = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int gender = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int lastname = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int list_cares = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int list_patients = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int new_care = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int new_patient = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int niss = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int oaidentification = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int oaregistration = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int patient = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int phone = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int save = 2131034120;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
